language: python
python:
  - 2.6
  - 2.7
  - 3.4
env:
  - DJANGO=1.4.14
  - DJANGO=1.5.9
  - DJANGO=1.6.6
  - DJANGO=1.7.2
install:
  - pip install https://github.com/django/django/archive/${DJANGO}.zip#egg=django
  - pip install -r tests/requirements.txt
  - python setup.py -q install
script:
  - coverage run --source=django_geoip manage.py test
after_success:
  - coveralls --verbose
matrix:
  exclude:
    - python: 3.4
      env: DJANGO=1.4.14
